# The Site Configuration

# Import the theme
theme: jekyll-theme-chirpy

# Change the following value to '/PROJECT_NAME' ONLY IF your site type is GitHub Pages Project sites
# and doesn't have a custom domain.
baseurl: ""

# The language of the webpage › http://www.lingoes.net/en/translator/langcode.htm
# If it has the same name as one of the files in folder `_data/locales`, the layout language will also be changed,
# otherwise, the layout language will use the default value of 'en'.
lang: en

# Change to your timezone › http://www.timezoneconverter.com/cgi-bin/findzone/findzone
timezone: Asia/Shanghai

# jekyll-seo-tag settings › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# ↓ --------------------------

title: Hao Liu's blog # the main title

tagline: Individuals and interactions over processes and tools, Responding to change over following a plan. # it will display as the sub-title

description: >- # used by seo meta and the atom feed
  生活和技术,以及折腾. code, paper, blog; iOS developer, swift

# fill in the protocol & hostname for your site, e.g., 'https://username.github.io'
url: "https://imhaoliu.com"

github:
  username: lyleLH # change to your github username

# twitter:
  # username: twitter_username # change to your twitter username

social:
  # Change to your full name.
  # It will be displayed as the default author of the posts and the copyright owner in the Footer
  name: Hao Liu
  email: v2top1lyle@gmail.com # change to your email address
  links:
    # The first element serves as the copyright owner's link
    # - https://twitter.com/username # change to your twitter homepage
    - https://github.com/lyleLH # change to your github homepage
    # Uncomment below to add more social links
    # - https://www.facebook.com/username
    - https://www.linkedin.com/in/haoliuv2top1

google_site_verification: # fill in to your verification string

# ↑ --------------------------
# The end of `jekyll-seo-tag` settings

google_analytics:
  id: G-RB9D8NZZ94 # fill in your Google Analytics ID
  # Google Analytics pageviews report settings
  pv:
    proxy_endpoint: # fill in the Google Analytics superProxy endpoint of Google App Engine
    cache_path: # the local PV cache data, friendly to visitors from GFW region

# Prefer color scheme setting.
#
# Note: Keep empty will follow the system prefer color by default,
# and there will be a toggle to switch the theme between dark and light
# on the bottom left of the sidebar.
#
# Available options:
#
#     light  - Use the light color scheme
#     dark   - Use the dark color scheme
#
theme_mode: # [light|dark]

# The CDN endpoint for images.
# Notice that once it is assigned, the CDN url
# will be added to all image (site avatar & posts' images) paths starting with '/'
#
# e.g. 'https://cdn.com'
img_cdn:

# the avatar on sidebar, support local or CORS resources
avatar: /assets/img/favicons/apple-touch-icon.png

# boolean type, the global switch for TOC in posts.
toc: true

comments:
  active: 'giscus'# The global switch for posts comments, e.g., 'disqus'.  Keep it empty means disable
  # The active options are as follows:
  disqus:
    shortname: # fill with the Disqus shortname. › https://help.disqus.com/en/articles/1717111-what-s-a-shortname
  # utterances settings › https://utteranc.es/
  utterances:
    repo: # <gh-username>/<repo>
    issue_term: # < url | pathname | title | ...>
  # Giscus options › https://giscus.app
  giscus:
    repo: lyleLH/lyleLH.github.io
    repo_id: R_kgDOIKaBIQ
    category: Q&A
    category_id: DIC_kwDOIKaBIc4CetAW
    mapping: # optional, default to 'pathname'
    input_position: # optional, default to 'bottom'
    lang: # optional, default to the value of `site.lang`
    reactions_enabled: # optional, default to the value of `1`

# Self-hosted static assets, optional › https://github.com/cotes2020/chirpy-static-assets
assets:
  self_host:
    enabled: # boolean, keep empty means false
    # specify the Jekyll environment, empty means both
    # only works if `assets.self_host.enabled` is 'true'
    env: # [development|production]

pwa:
  enabled: true # the option for PWA feature

paginate: 10

# ------------ The following options are not recommended to be modified ------------------

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: "" # An empty string here means all files in the project
      type: posts
    values:
      layout: post
      comments: true # Enable comments in posts.
      toc: true # Display TOC column in posts.
      # DO NOT modify the following parameter unless you are confident enough
      # to update the code of all other post links in this project.
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs # see `site.collections`
    values:
      layout: page
      permalink: /:title/
  - scope:
      path: assets/img/favicons
    values:
      swcache: true
  - scope:
      path: assets/js/dist
    values:
      swcache: true

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - tools
  - README.md
  - CHANGELOG.md
  - LICENSE
  - rollup.config.js
  - node_modules
  - package*.json

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/


## => Plugins
##############################
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji



links_left:
  - title: 友链名称1
    url: https://example.com/link1
    description: 这是友链1的描述。
    avatar: https://blog.03k.org/favicon.ico
  - title: 友链名称2
    url: https://example.com/link2
    description: 这是友链2的描述。
    avatar: https://blog.03k.org/favicon.ico
  - title: 友链名称1
    url: https://example.com/link1
    description: 这是友链1的描述。
    avatar: https://blog.03k.org/favicon.ico
  - title: 友链名称2
    url: https://example.com/link2
    description: 这是友链2的描述。
    avatar: https://blog.03k.org/favicon.ico
  - title: 友链名称1
    url: https://example.com/link1
    description: 这是友链1的描述。
    avatar: https://blog.03k.org/favicon.ico
  - title: 友链名称2
    url: https://example.com/link2
    description: 这是友链2的描述。
    avatar: https://blog.03k.org/favicon.ico
  - title: 友链名称1
    url: https://example.com/link1
    description: 这是友链1的描述。
    avatar: https://blog.03k.org/favicon.ico
  - title: 友链名称2
    url: https://example.com/link2
    description: 这是友链2的描述。
    avatar: https://blog.03k.org/favicon.ico
  - title: 友链名称1
    url: https://example.com/link1
    description: 这是友链1的描述。
    avatar: https://blog.03k.org/favicon.ico
  - title: 友链名称2
    url: https://example.com/link2
    description: 这是友链2的描述。
    avatar: https://blog.03k.org/favicon.ico
  - title: 友链名称1
    url: https://example.com/link1
    description: 这是友链1的描述。
    avatar: https://blog.03k.org/favicon.ico
  - title: 友链名称2
    url: https://example.com/link2
    description: 这是友链2的描述。
    avatar: https://blog.03k.org/favicon.ico

links_right:
  - title: 友链名称3
    url: https://example.com/link3
    description: 这是友链3的描述。
    avatar: https://blog.03k.org/favicon.ico
  - title: 友链名称4
    url: https://example.com/link4
    description: 这是友链4的描述。
    avatar: https://blog.03k.org/favicon.ico

 